### Book: Python for Data Analysis
`Author: Wes McKinney`


Two main data structures
* **Series**
* **DataFrame**

In [2]:
# import libraries
import pandas as pd
import numpy as np

In [3]:
dates = pd.Series([52,69,71])
dates

0    52
1    69
2    71
dtype: int64

In [4]:
dates2 = pd.Series([52,69,71],index = ['Language Movement', '1969 Mass Uprising','Liberation War'])
dates2


Language Movement     52
1969 Mass Uprising    69
Liberation War        71
dtype: int64

In [5]:
dates.index

RangeIndex(start=0, stop=3, step=1)

In [6]:
dates2.values

array([52, 69, 71])

In [7]:
# create a new data frame
student_age = pd.Series([23,21,24,23,24])


In [8]:
student_age[student_age >22]

0    23
2    24
3    23
4    24
dtype: int64

In [9]:
student_age*2

0    46
1    42
2    48
3    46
4    48
dtype: int64

In [10]:
np.exp(student_age)

0    9.744803e+09
1    1.318816e+09
2    2.648912e+10
3    9.744803e+09
4    2.648912e+10
dtype: float64

In [11]:
# creating a series from dictionary
capital_of_country = {'Bangladesh':'Dhaka','India':'Delhi','Pakistan':'Karachi','Nepal':"Katmandu"}
capital = pd.Series(capital_of_country)
capital

Bangladesh       Dhaka
India            Delhi
Pakistan       Karachi
Nepal         Katmandu
dtype: object

In [12]:
capital.index.name = "Country"
capital

Country
Bangladesh       Dhaka
India            Delhi
Pakistan       Karachi
Nepal         Katmandu
dtype: object

In [13]:
capital.index[0]

'Bangladesh'

* ###  DataFrame

In [14]:
country = {'name':['Bangladesh','India','Pakistan','Nepal','Bhutan','Maldives','Afghanistan'],
           'year':[1971,1947,1947,1923,1949,1965,1919],
           'population':[164,1380,220,29,7,5,38]}
            #population counts in million 
df = pd.DataFrame(country)
df

name  year  population
0   Bangladesh  1971         164
1        India  1947        1380
2     Pakistan  1947         220
3        Nepal  1923          29
4       Bhutan  1949           7
5     Maldives  1965           5
6  Afghanistan  1919          38

In [15]:
import numpy 
import numpy as np
from numpy import array

In [16]:
np.array

<function numpy.array>

In [17]:
df = pd.DataFrame(country, columns = ['name', 'population', 'year'])
df

name  population  year
0   Bangladesh         164  1971
1        India        1380  1947
2     Pakistan         220  1947
3        Nepal          29  1923
4       Bhutan           7  1949
5     Maldives           5  1965
6  Afghanistan          38  1919

In [18]:
df = pd.DataFrame(country, columns = ['name', 'population', 'year','gdp'])
df

name  population  year  gdp
0   Bangladesh         164  1971  NaN
1        India        1380  1947  NaN
2     Pakistan         220  1947  NaN
3        Nepal          29  1923  NaN
4       Bhutan           7  1949  NaN
5     Maldives           5  1965  NaN
6  Afghanistan          38  1919  NaN

In [19]:
df.name

0     Bangladesh
1          India
2       Pakistan
3          Nepal
4         Bhutan
5       Maldives
6    Afghanistan
Name: name, dtype: object

In [20]:
# accedding a row
df.loc[3]

name          Nepal
population       29
year           1923
gdp             NaN
Name: 3, dtype: object

In [21]:
# gdp counts in billion 
df['gdp'] = [324,2623,263,33,2,4,19]
df

name  population  year   gdp
0   Bangladesh         164  1971   324
1        India        1380  1947  2623
2     Pakistan         220  1947   263
3        Nepal          29  1923    33
4       Bhutan           7  1949     2
5     Maldives           5  1965     4
6  Afghanistan          38  1919    19

In [22]:
df.T

0      1         2      3       4         5            6
name        Bangladesh  India  Pakistan  Nepal  Bhutan  Maldives  Afghanistan
population         164   1380       220     29       7         5           38
year              1971   1947      1947   1923    1949      1965         1919
gdp                324   2623       263     33       2         4           19

* ## Index Objects


In [23]:
obj = pd.DataFrame(range(3), index = ['a','b','c'])
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [24]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [25]:
# index[1] = 'd'
# index objects are immutable 

In [26]:
df.columns

Index(['name', 'population', 'year', 'gdp'], dtype='object')

In [27]:
'gdp' in df.columns

True

In [28]:
# you can use duplicate index name

* ## Esstential Functionality
* ### Reindexing

In [29]:
obj = pd.Series([10,20,30,40], index = ['a','b','c','d'])
obj

a    10
b    20
c    30
d    40
dtype: int64

In [30]:
obj2 = obj.reindex(['a','b','c','d','e'], method = 'ffill')
obj2

a    10
b    20
c    30
d    40
e    40
dtype: int64

In [31]:
# lets fill up NaN value with forward fill method
obj3 = pd.Series(['red', 'green', 'blue','orange'], index = [0,1,2,3])
obj3.reindex(range(6), method = 'ffill')

0       red
1     green
2      blue
3    orange
4    orange
5    orange
dtype: object

In [32]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), index=['a','b','c'],columns=['A','B','C'])
frame

A  B  C
a  0  1  2
b  3  4  5
c  6  7  8

In [33]:
frame2 = frame.reindex(['a','b','c','d','e'])
frame2

A    B    C
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  NaN  NaN  NaN
e  NaN  NaN  NaN

In [34]:
# dropping values
# row is considered as axis = 0
newframe = frame2.drop(['d','e']) # you can put axis = 0
newframe


A    B    C
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0

In [35]:
newframe.drop(['B'], axis = 1)

A    C
a  0.0  2.0
b  3.0  5.0
c  6.0  8.0

In [36]:
newframe.drop('b', axis = 0, inplace=True)
newframe

A    B    C
a  0.0  1.0  2.0
c  6.0  7.0  8.0

In [37]:
obj3

0       red
1     green
2      blue
3    orange
dtype: object

In [38]:
obj3[2:4]


2      blue
3    orange
dtype: object

In [39]:
obj3[[1,3]]

1     green
3    orange
dtype: object

In [40]:
obj3[obj3=='green']

1    green
dtype: object

In [41]:
obj3[2:4] = 'yellow'
obj3

0       red
1     green
2    yellow
3    yellow
dtype: object

In [42]:
data = pd.DataFrame(np.random.randint(20,45,24).reshape(4,6),
                   columns = ['January','February','March','April','May','June'],
                   index = ['Rajshahi', 'Dhaka', 'Khulna','Sylhet'])
data

January  February  March  April  May  June
Rajshahi       28        39     38     21   41    22
Dhaka          36        35     25     32   29    34
Khulna         25        41     31     25   27    31
Sylhet         34        21     35     38   38    40

In [43]:
data[['January','June']]

January  June
Rajshahi       28    22
Dhaka          36    34
Khulna         25    31
Sylhet         34    40

* ### loc and iloc

In [44]:
data.loc['Rajshahi']

January     28
February    39
March       38
April       21
May         41
June        22
Name: Rajshahi, dtype: int64

In [45]:
data < 30

January  February  March  April    May   June
Rajshahi     True     False  False   True  False   True
Dhaka       False     False   True  False   True  False
Khulna       True     False  False   True   True  False
Sylhet      False      True  False  False  False  False

In [46]:
data[data > 40] = 0
data

January  February  March  April  May  June
Rajshahi       28        39     38     21    0    22
Dhaka          36        35     25     32   29    34
Khulna         25         0     31     25   27    31
Sylhet         34        21     35     38   38    40

In [47]:
# loc and iloc
data.loc['Rajshahi',['January','June']]

January    28
June       22
Name: Rajshahi, dtype: int64

In [48]:
data.iloc[0,[0,-1]]

January    28
June       22
Name: Rajshahi, dtype: int64

In [49]:
data.iloc[-2:]

January  February  March  April  May  June
Khulna       25         0     31     25   27    31
Sylhet       34        21     35     38   38    40

In [50]:
data.loc[['Rajshahi','Sylhet'],['January','June']]

January  June
Rajshahi       28    22
Sylhet         34    40

* ### Arithmetic and Data Alignment

In [51]:
s1 = pd.Series(np.random.randint(12,39,5), index=['a','b','c','d','e'])
s2 = pd.Series(np.random.randint(10,30,5), index=['a','g','c','f','e'])
s1 + s2                                                  
# s1 - s2, s1 / s2, s1 * s2                                                  

a    37.0
b     NaN
c    50.0
d     NaN
e    56.0
f     NaN
g     NaN
dtype: float64

In [52]:
df1 = pd.DataFrame(np.random.randint(28,45,16).reshape(4,4),
                   columns = list('abcd'), 
                   index = ['Dhaka','Rajshahi','Chittagong','Barishal'])
df2 = pd.DataFrame(np.random.randint(10,45,16).reshape(4,4),
                   columns = list('abcd'), 
                   index = ['Khulna','Rajshahi','Rangpur','Barishal'])
df1

a   b   c   d
Dhaka       42  31  31  28
Rajshahi    40  42  43  41
Chittagong  31  30  35  28
Barishal    33  32  40  35

In [53]:
df2

a   b   c   d
Khulna    28  38  24  20
Rajshahi  41  27  25  12
Rangpur   13  11  36  22
Barishal  12  22  12  17

In [54]:
df1+df2

a     b     c     d
Barishal    45.0  54.0  52.0  52.0
Chittagong   NaN   NaN   NaN   NaN
Dhaka        NaN   NaN   NaN   NaN
Khulna       NaN   NaN   NaN   NaN
Rajshahi    81.0  69.0  68.0  53.0
Rangpur      NaN   NaN   NaN   NaN

In [55]:
df2.loc[['Rangpur','Barishal'],['a','c']] = np.nan
df2

a   b     c   d
Khulna    28.0  38  24.0  20
Rajshahi  41.0  27  25.0  12
Rangpur    NaN  11   NaN  22
Barishal   NaN  22   NaN  17

In [56]:
df1

a   b   c   d
Dhaka       42  31  31  28
Rajshahi    40  42  43  41
Chittagong  31  30  35  28
Barishal    33  32  40  35

In [57]:
df2

a   b     c   d
Khulna    28.0  38  24.0  20
Rajshahi  41.0  27  25.0  12
Rangpur    NaN  11   NaN  22
Barishal   NaN  22   NaN  17

In [58]:
df3 = df2.add(df1, fill_value=0)
df3

a     b     c     d
Barishal    33.0  54.0  40.0  52.0
Chittagong  31.0  30.0  35.0  28.0
Dhaka       42.0  31.0  31.0  28.0
Khulna      28.0  38.0  24.0  20.0
Rajshahi    81.0  69.0  68.0  53.0
Rangpur      NaN  11.0   NaN  22.0

In [59]:
1/df3
df3.rdiv(1)

a         b         c         d
Barishal    0.030303  0.018519  0.025000  0.019231
Chittagong  0.032258  0.033333  0.028571  0.035714
Dhaka       0.023810  0.032258  0.032258  0.035714
Khulna      0.035714  0.026316  0.041667  0.050000
Rajshahi    0.012346  0.014493  0.014706  0.018868
Rangpur          NaN  0.090909       NaN  0.045455

In [60]:
df3.reindex(columns=df2.columns, fill_value=0)
df3

a     b     c     d
Barishal    33.0  54.0  40.0  52.0
Chittagong  31.0  30.0  35.0  28.0
Dhaka       42.0  31.0  31.0  28.0
Khulna      28.0  38.0  24.0  20.0
Rajshahi    81.0  69.0  68.0  53.0
Rangpur      NaN  11.0   NaN  22.0

* ### Operations between DataFrame and Series

In [61]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
arr[0]

array([0, 1, 2])

In [63]:
# here arr[0] subtracts from arr for each row
# this is called as broadcasting of arrays
arr-arr[0]

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6],
       [9, 9, 9]])

In [64]:
frame = pd.DataFrame(np.arange(12).reshape(4,3),
                    columns = list('abe'),
                    index=['A','B','C','D'])
frame

a   b   e
A  0   1   2
B  3   4   5
C  6   7   8
D  9  10  11

In [65]:
series = frame.iloc[0]
series

a    0
b    1
e    2
Name: A, dtype: int64

In [66]:
frame - series

a  b  e
A  0  0  0
B  3  3  3
C  6  6  6
D  9  9  9

In [67]:
series2 = pd.Series(range(3), index=list('bde'))
series2

b    0
d    1
e    2
dtype: int64

In [68]:
frame+series2

a     b   d     e
A NaN   1.0 NaN   4.0
B NaN   4.0 NaN   7.0
C NaN   7.0 NaN  10.0
D NaN  10.0 NaN  13.0

In [69]:
series3 = frame['b']
series3

A     1
B     4
C     7
D    10
Name: b, dtype: int64

In [70]:
frame.sub(series2, axis=1)

a     b   d    e
A NaN   1.0 NaN  0.0
B NaN   4.0 NaN  3.0
C NaN   7.0 NaN  6.0
D NaN  10.0 NaN  9.0

* ### Function Application and Mapping


In [71]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                     index = ['Mirpur','Mohammadpur','Uttara','Banani'])
frame

b         d         e
Mirpur      -1.823304  0.665459 -0.325841
Mohammadpur -0.791990 -0.080257  0.021532
Uttara       1.115998 -0.867065  0.327118
Banani      -0.057871  1.280371 -0.303087

In [72]:
abs(frame)

b         d         e
Mirpur       1.823304  0.665459  0.325841
Mohammadpur  0.791990  0.080257  0.021532
Uttara       1.115998  0.867065  0.327118
Banani       0.057871  1.280371  0.303087

In [73]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.939302
d    2.147436
e    0.652959
dtype: float64

In [74]:
frame.apply(f, axis=0)

b    2.939302
d    2.147436
e    0.652959
dtype: float64

In [75]:
frame.apply(f, axis=1)

Mirpur         2.488763
Mohammadpur    0.813522
Uttara         1.983063
Banani         1.583457
dtype: float64

In [76]:
frame.applymap(lambda x: '%.2f'%x)

b      d      e
Mirpur       -1.82   0.67  -0.33
Mohammadpur  -0.79  -0.08   0.02
Uttara        1.12  -0.87   0.33
Banani       -0.06   1.28  -0.30

In [77]:
frame['b'].map(lambda x:'%.2f'%x)

Mirpur         -1.82
Mohammadpur    -0.79
Uttara          1.12
Banani         -0.06
Name: b, dtype: object

* ### Sorting and Ranking

In [78]:
obj = pd.Series(range(4), index = ['d','a','e','b'])
obj.sort_index()

a    1
b    3
d    0
e    2
dtype: int64

In [79]:
frame = pd.DataFrame(np.arange(8).reshape(4,2),
                    index=['three','two','one','four'],
                    columns=['B','A']);
frame.sort_index()
# usally sort by alphabetically order and from lowest to highest number

B  A
four   6  7
one    4  5
three  0  1
two    2  3

In [80]:
frame.sort_index(axis=1)

A  B
three  1  0
two    3  2
one    5  4
four   7  6

In [81]:
19/7

2.7142857142857144

In [82]:
7-2.71

4.29

In [83]:
df = pd.DataFrame(np.random.randn(3,4), index=['a','a','b'])
df.index.is_unique

False

In [84]:
df.loc['a']

0         1         2         3
a -0.714257  1.526098  0.190689 -0.693856
a -0.276102  0.257351  0.403384 -2.189148

## Summarizing and Computing Descriptive Statistcs

In [85]:
df = pd.DataFrame([[1.5, np.nan],[7.1,-5.5],[np.nan, np.nan],[.75, -1.5]], 
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])
df

one  two
a  1.50  NaN
b  7.10 -5.5
c   NaN  NaN
d  0.75 -1.5

In [86]:
df.sum()

one    9.35
two   -7.00
dtype: float64

In [87]:
df.sum(axis=1)

a    1.50
b    1.60
c    0.00
d   -0.75
dtype: float64

In [88]:
df.mean()

one    3.116667
two   -3.500000
dtype: float64

In [89]:
df.mean(axis=1)

a    1.500
b    0.800
c      NaN
d   -0.375
dtype: float64

In [90]:
df.cumsum()

one  two
a  1.50  NaN
b  8.60 -5.5
c   NaN  NaN
d  9.35 -7.0

In [91]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.116667 -3.500000
std    3.469990  2.828427
min    0.750000 -5.500000
25%    1.125000 -4.500000
50%    1.500000 -3.500000
75%    4.300000 -2.500000
max    7.100000 -1.500000

In [94]:
import pandas_datareader.data as web 

In [99]:
price  = pd.DataFrame([data['Adj Close']
                       for _, data in all_data.items()], columns=all_data.keys())
volume = pd.DataFrame([data['Volume']
                       for _, data in all_data.items()], columns=all_data.keys())


NameError: name 'all_data' is not defined

In [ ]:
returns = price.pct_change()
type(returns)

pandas.core.frame.DataFrame

In [ ]:
returns.shape

(1258, 4)

In [ ]:
returns.head(10)

AAPL       IBM      MSFT      GOOG
Date                                              
2017-09-27       NaN       NaN       NaN       NaN
2017-09-28 -0.006160  0.000000  0.000271  0.005304
2017-09-29  0.005481 -0.003982  0.008393  0.010121
2017-10-02 -0.002011  0.010890  0.001611 -0.006089
2017-10-03  0.004356  0.000818 -0.004691  0.004742
2017-10-04 -0.006473 -0.002044  0.005791 -0.006379
2017-10-05  0.012445  0.001639  0.017137  0.019208
2017-10-06 -0.000579 -0.001636  0.000395  0.009207
2017-10-09  0.003477  0.006212  0.003815 -0.001931
2017-10-10  0.000385  0.007531  0.000000 -0.004504

In [ ]:
# calculate correlation
returns.GOOG.corr(returns.IBM)
returns['GOOG'].corr(returns['IBM'])

0.45009008443564863

In [ ]:
# Covariance
returns['GOOG'].cov(returns['IBM'])

0.000146825888246252

In [ ]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.440942  0.762441  0.688815
IBM   0.440942  1.000000  0.482654  0.450090
MSFT  0.762441  0.482654  1.000000  0.790973
GOOG  0.688815  0.450090  0.790973  1.000000

In [ ]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000417  0.000155  0.000294  0.000266
IBM   0.000155  0.000297  0.000157  0.000147
MSFT  0.000294  0.000157  0.000356  0.000283
GOOG  0.000266  0.000147  0.000283  0.000358

In [ ]:
returns.corrwith(returns.IBM)

AAPL    0.440942
IBM     1.000000
MSFT    0.482654
GOOG    0.450090
dtype: float64

* ### Unique values, value counts, and Membership

In [ ]:
obj = pd.Series(['a','a','b','b','c','e','e','f','f','g','g'])
uniques = obj.unique()
uniques

array(['a', 'b', 'c', 'e', 'f', 'g'], dtype=object)

In [ ]:
obj.value_counts()

a    2
b    2
e    2
f    2
g    2
c    1
dtype: int64

In [ ]:
pd.value_counts(obj.values, sort = False)


a    2
b    2
c    1
e    2
f    2
g    2
dtype: int64

In [ ]:
obj

0     a
1     a
2     b
3     b
4     c
5     e
6     e
7     f
8     f
9     g
10    g
dtype: object

In [ ]:
mask = obj.isin(['b','g'])
mask

0     False
1     False
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10     True
dtype: bool

In [ ]:
data = pd.DataFrame({'Ch1': [1,4,2,3,4,6],
                    'Ch2': [1,4,2,3,4,3],
                    'Ch3': [1,4,2,3,5,5]})
data

Ch1  Ch2  Ch3
0    1    1    1
1    4    4    4
2    2    2    2
3    3    3    3
4    4    4    5
5    6    3    5

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

Ch1  Ch2  Ch3
1  1.0  1.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  1.0
4  2.0  2.0  1.0
5  0.0  0.0  2.0
6  1.0  0.0  0.0